// examples/react/src/app/index.tsx
import { createFileRoute } from "@tanstack/react-router";

import { UContainer, UIcon, UImage, UMain } from "#build/ui/components";

export const Route = createFileRoute("/")({
  component: Page,
  head: () => ({
    meta: [{ title: "Veehance UI" }],
  }),
});

function Page() {
  return (
    <UMain className="flex min-h-screen flex-col items-center justify-center">
      <UContainer className="flex flex-col items-center justify-center gap-8 lg:grow">
        <div className="flex gap-2">
          <UImage
            src="https://logo.svgcdn.com/logos/vitejs.png"
            alt="Framework"
            height={64}
            width={64}
          />
        </div>
        <h1 className="font-bold text-5xl md:text-7xl">Veehance UI</h1>
        <div className="flex gap-2">
          <div className="size-8 rounded-xs border border-default bg-primary"></div>
          <div className="size-8 rounded-xs border border-default bg-secondary"></div>
          <div className="size-8 rounded-xs border border-default bg-default"></div>
          <div className="size-8 rounded-xs border border-default bg-muted"></div>
          <div className="size-8 rounded-xs border border-default bg-elevated"></div>
          <div className="size-8 rounded-xs border border-default bg-accented"></div>
          <div className="size-8 rounded-xs border border-default bg-inverted"></div>
          <div className="size-8 rounded-xs border border-default bg-success"></div>
          <div className="size-8 rounded-xs border border-default bg-info"></div>
          <div className="size-8 rounded-xs border border-default bg-warning"></div>
          <div className="size-8 rounded-xs border border-default bg-error"></div>
        </div>
        <div className="flex gap-2">
          <span className="text-dimmed">Dimmed</span>
          <span className="text-muted">Muted</span>
          <span className="text-toned">Toned</span>
          <span className="text-default">Default</span>
          <span className="text-highlighted">Highlighted</span>
        </div>
        <div className="flex gap-2">
          <UIcon name="dark" className="size-6" />
          <UIcon name="light" className="size-6" />
          <UIcon name="system" className="size-6" />
          <UIcon name="user" className="size-6" />
        </div>
      </UContainer>
    </UMain>
  );
}

// examples/vue/src/app.vue
<script setup lang="ts">
import UImage from "#build/image";
import ULink from "#build/link";

const appConfig = useAppConfig();
console.log(appConfig.ui);
</script>

<template>
  <UMain class="flex min-h-screen flex-col items-center justify-center">
    <UContainer class="flex flex-col items-center justify-center gap-8 opacity-100 starting:opacity-0 transition-opacity duration-750 lg:grow">
      <div class="flex gap-2">
        <UImage class="size-16" src="https://logo.svgcdn.com/logos/vitejs.png" alt="framework"/>
      </div>
      <h1 class="font-bold text-5xl md:text-7xl">Veehance UI</h1>
      <div class="flex gap-2">
        <div class="size-8 rounded-xs border border-default bg-primary"></div>
        <div class="size-8 rounded-xs border border-default bg-secondary"></div>
        <div class="size-8 rounded-xs border border-default bg-default"></div>
        <div class="size-8 rounded-xs border border-default bg-muted"></div>
        <div class="size-8 rounded-xs border border-default bg-elevated"></div>
        <div class="size-8 rounded-xs border border-default bg-accented"></div>
        <div class="size-8 rounded-xs border border-default bg-inverted"></div>
        <div class="size-8 rounded-xs border border-default bg-success"></div>
        <div class="size-8 rounded-xs border border-default bg-info"></div>
        <div class="size-8 rounded-xs border border-default bg-warning"></div>
        <div class="size-8 rounded-xs border border-default bg-error"></div>
      </div>
      <div class="flex gap-2">
        <span class="text-dimmed">Dimmed</span>
        <span class="text-muted">Muted</span>
        <span class="text-toned">Toned</span>
        <span class="text-default">Default</span>
        <span class="text-highlighted">Highlighted</span>
      </div>
      <div class="flex gap-2">
        <UIcon name="dark" class="size-6" />
        <UIcon name="light" class="size-6" />
        <UIcon name="system" class="size-6" />
        <UIcon name="user" class="size-6" />
      </div>
      <div class="flex gap-2">
        <ULink as="button" to="/#">Playground</ULink>
      </div>
    </UContainer>
  </UMain>
</template>
