// packages/react/src/lib/components/Container.tsx
import type { ClassValue } from "@veehance/core/types";
import { cx } from "@veehance/core/utils";

export type ContainerProps = React.ComponentProps<"div"> & {
  className?: ClassValue;
};

function Container({ className, ...props }: ContainerProps) {
  return <div data-slot="container" className={cx(className)} {...props} />;
}

export default Container;

// packages/svelte/src/lib/components/Container.svelte
<script lang="ts">
import type { ClassValue } from "@veehance/core/types";
import { cx } from "@veehance/core/utils";

import type { HTMLAttributes } from "svelte/elements";

export interface ContainerProps
  extends Omit<HTMLAttributes<HTMLDivElement>, "class"> {
  class?: ClassValue;
}

let { class: className, children, ...restProps }: ContainerProps = $props();
</script>

<div data-slot="container" class={cx(className)} {...restProps}>
  {@render children?.()}
</div>
