// packages/react/src/lib/components/Main.tsx
import type { ClassValue } from "@veehance/core/types";
import { cx } from "@veehance/core/utils";

export type MainProps = React.ComponentProps<"main"> & {
  className?: ClassValue;
};

function Main({ className, ...props }: MainProps) {
  return <main data-slot="main" className={cx(className)} {...props} />;
}

export default Main;

// packages/vue/src/lib/components/Main.vue
<script lang="ts">
import type { ClassValue } from "@veehance/core/types";

export interface MainProps {
  as?: any;
  class?: ClassValue;
}

export interface MainSlots {
  default(props?: object): any;
}
</script>

<script setup lang="ts">
import { cx } from "@veehance/core/utils";

import { Primitive } from "reka-ui";
import { computed } from "vue";

const props = withDefaults(defineProps<MainProps>(), { as: "main" });
defineSlots<MainSlots>();
</script>

<template>
  <Primitive :as="as" data-slot="main" :class="cx(props.class)">
    <slot />
  </Primitive>
</template>
