// packages/react/src/lib/components/ui/Main.tsx
import type { ClassValue, Component } from "@veehance/core/types";
import { cv } from "@veehance/core/utils";

import theme from "#build/theme/main";
import { useAppConfig } from "#build/ui/imports";

type Main = Component<typeof theme, "main", "ui">;

export type MainProps = React.ComponentProps<"main"> & {
  className?: ClassValue;
};

function Main({ className, ...props }: MainProps) {
  const appConfig = useAppConfig() as Main["config"];

  const ui = cv({
    extend: cv(theme),
    ...(appConfig.ui?.components?.main || {}),
  });

  return (
    <main data-slot="main" className={ui({ className }) as any} {...props} />
  );
}

export default Main;

// packages/ui/src/runtime/components/elements/ui/Main.vue
<script lang="ts">
import type { AppConfig } from "@nuxt/schema";

import _appConfig from "#build/app.config";
import theme from "#build/ui/main";

import { tv } from "../../../utils/class";

const appConfig = _appConfig as AppConfig & {
  ui: { components: { main: Partial<typeof theme> } };
};

const main = tv({
  extend: tv(theme),
  ...(appConfig.ui?.components?.main || {}),
});

export interface MainProps {
  class?: any;
}

export interface MainSlots {
  default: (props?: object) => any;
}
</script>

<script setup lang="ts">
import { Primitive } from "reka-ui";

const props = defineProps<MainProps>();
defineSlots<MainSlots>();
</script>

<template>
  <Primitive as="main" :class="main({ class: props.class })">
    <slot />
  </Primitive>
</template>
